DATA:
    Data_path: /data2/NTU_data/resize_mb_fd_4   
    TRAIN_FILE: /data2/Real60/txt_file/NTU120_XSet_train.txt
    VAL_FILE: /data2/Real60/txt_file/NTU120_XSet_val.txt
    NUM_FRAMES: 8
    NUM_CLASSES: 120
    LABEL_LIST: /data2/Real60/ntu120_label_name.txt
    BENCHMARK: NTU120-XSet 
MODEL:
    ARCH: ViT-B/16
TRAIN:
    BATCH_SIZE: 4 
    ACCUMULATION_STEPS: 2
    NUM_WORKERS: 8 
TEST:
    BATCH_SIZE: 16 